if(!place_meeting(x,y,par_tower)&&!place_meeting(x,y,obj_blocked)){
	if(instance_exists(con_level)){
		if(con_level.money>=cost){
			con_level.money-=cost;
			instance_create_layer(x,y,"Instances",tower);
		}
	}
	instance_destroy();
}
